### ISSUE TITLE
Most of the Code.js and notes.txt file are dups

### ISSUE THREAD

**Issue by rohitdash08** [SartHak-0-Sach/Harkirat-Singh-course_code_and_notes#13]
all the folder contains multiple code.js and notes.txt file which are same.

**Comment by SartHak-0-Sach** [comment]
Hi @rohitdash08, so I have currently been really busy with my internship and had exams so I haven't really updated any content here and all those are simple dummy files that have been added there

But in the upcoming month I will try my best to fast forward this cohort and add all notes and code I can

Sorry for the delay.

**Comment by rohitdash08** [comment]
instead of copy pasting someone else's effort, try to make it your own otherwise I'll have to tell harkirat about this repo

**Comment by SartHak-0-Sach** [comment]
> instead of copy pasting someone else's effort, try to make it your own otherwise I'll have to tell harkirat about this repo

copy pasting someone else's efforts?? I bought this course very late so I haven't got the time to do much in it but I haven't copied anything from anyone too. All the notes that have been mentioned in it are all mine that I made myself.

And will be doing the same in future.

Nothing in this is unethical that harkirat will be offended by it as this is my code and my explanation of concept and my version of solutions to assignments that I have solved.

If you want you can ask harkirat himself what unethical stuff have I done here.
