### ISSUE TITLE
I guess there is some issue in printHelloAsync function  code and our  expectations. 

### ISSUE THREAD

**Issue by Harshal0506** [SartHak-0-Sach/Harkirat-Singh-course_code_and_notes#14]
In Week-02=Advanced JS and Bash/lec-1=Revision of promises/code.js

I guess printHelloAfterDelay needs modification.

```
async function printHelloAsync() {
    await delay(1000);
    SayingHello();

    await printHelloAfterDelay(2000, 2);

    await printHelloAfterDelay(3000, 3);
}

```

**To have a clear view** 

```
async function printHelloAsync(){
    await delay(5000);
   SayingHello();
    await printHelloAfterDelay(5000,2); // something new to learn here
 
    console.log("I am being runned ");
    await printHelloAfterDelay(5000,3);



}
```

 **Just run the above code you will see  5 hello is being printed together await is not letting you wait till all hello of printHelloAfterDelay is printed, I guess code modification is needed**  

I have just started with course ,  thankyou for your repository. Let me know if I am wrong somewhere.

**Comment by Harshal0506** [comment]
```
function delay(ms){
    return new Promise((resolve,reject)=>{

        setTimeout(()=>{resolve()}, ms);
    });
}


SayingHello =()=> console.log("Hello");

function printHelloAfterDelay(delayTime,times){

 return new Promise((resolve,reject)=>{

    delay(delayTime).then(()=>{
        for(let i=0;i<times;i++){
        SayingHello();
        }
        resolve();
    
      });

 })
  


}


// using async await 
async function printHelloAsync(){
    await delay(5000);
    SayingHello();
    await printHelloAfterDelay(5000,2); // something new to learn here
 
    console.log("I am being runned ");
    await printHelloAfterDelay(5000,3);



}

printHelloAsync();
```

Let me know if I am wrong somewhere.

**Comment by SartHak-0-Sach** [comment]
https://github.com/SartHak-0-Sach/Harkirat-Singh-course_code_and_notes/assets/100426549/6b9b94ce-a5c0-45a3-aa6b-53dc2b2e14f3

I think you are mistaken, because it's working just fine for me, here's a screen recording of the same.

Can you please tell me the IDE you are using so I can assist you better, and if its a local IDE make sure the versions of node and IDE itself is up to date even though it shouldn't make a difference in my opinion.

**Comment by Harshal0506** [comment]
```
function delay(ms){
    return new Promise((resolve,reject)=>{

        setTimeout(()=>{resolve()}, ms);
    });
}


SayingHello =()=> console.log("Hello");

function printHelloAfterDelay(delayTime,times){

//  return new Promise((resolve,reject)=>{

    delay(delayTime).then(()=>{
        for(let i=0;i<times;i++){
        SayingHello();
        }
        // resolve();
    
      });

//  })
  


}


// using async await 
async function printHelloAsync(){
    await delay(5000);
    SayingHello();
    await printHelloAfterDelay(5000,2); // something new to learn here
 
    console.log("I am being runned ");
    await printHelloAfterDelay(5000,3);



}

printHelloAsync();
```

Run above code on[ this website ]( https://www.programiz.com/javascript/online-compiler/) 
printHelloAfterDelay does not return promise ( as it was in your code ). Let me know if you are seeing the output same way

I see output as 

```
Hello
I am being runned 
Hello  
Hello
Hello
Hello
Hello

```

**Comment by SartHak-0-Sach** [comment]
http://latentflip.com/loupe/?code=JC5vbignYnV0dG9uJywgJ2NsaWNrJywgZnVuY3Rpb24gb25DbGljaygpIHsKICAgIHNldFRpbWVvdXQoZnVuY3Rpb24gdGltZXIoKSB7CiAgICAgICAgY29uc29sZS5sb2coJ1lvdSBjbGlja2VkIHRoZSBidXR0b24hJyk7ICAgIAogICAgfSwgMjAwMCk7Cn0pOwoKY29uc29sZS5sb2coIkhpISIpOwoKc2V0VGltZW91dChmdW5jdGlvbiB0aW1lb3V0KCkgewogICAgY29uc29sZS5sb2coIkNsaWNrIHRoZSBidXR0b24hIik7Cn0sIDUwMDApOwoKY29uc29sZS5sb2coIldlbGNvbWUgdG8gbG91cGUuIik7!!!PGJ1dHRvbj5DbGljayBtZSE8L2J1dHRvbj4%3D

You can use this website to check how a certain code functions behind the scene and understand it better in case you think there are any issues in it
